# Generated by Django 3.0 on 2021-08-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=255, unique=True)),
                ('genre', models.CharField(max_length=100)),
                ('pages', models.IntegerField()),
                ('image', models.CharField(max_length=255)),
                ('published', models.CharField(max_length=100)),
            ],
        ),
    ]
