# Generated by Django 3.0 on 2021-08-30 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210830_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='copy_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copy_sender', to='api.Copy'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='copy_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copy_receiver', to='api.Copy'),
        ),
    ]
