# Generated by Django 3.0 on 2021-08-31 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210831_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='from_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='req_sent_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trade',
            name='to_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='req_sent_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
